# Site settings
title: Marc Liu
description: A place to write

# Build settings
markdown: kramdown
permalink: /:title/

# GitHub Pages settings
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

# Comments settings
comments_dir: _data/comments

# GitHub repository settings (for PR-based comments)
github:
  owner_name: lsm
  repository_name: lsm.github.io

# Plugins
plugins:
  - jekyll-feed

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git